version: '3.8'

services:
  app:
    build: .
    command: >
      sh -c "if [ \"$NODE_ENV\" = 'production' ]; then
        npm run build && serve -s dist -l 5173;
      else
        npm run dev;
      fi"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    networks:
      - porto-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  porto-network:
    driver: bridge